// <auto-generated />
using System;
using DonationWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DonationWebApp.Migrations.Goods
{
    [DbContext(typeof(GoodsContext))]
    [Migration("20230115190642_Goods")]
    partial class Goods
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DonationWebApp.Models.GoodsClass", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddNewCategory")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("DateOfDonation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionOfItem")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Donor")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("NumberOfItems")
                        .HasColumnType("int");

                    b.HasKey("DonorId");

                    b.ToTable("GoodDonation");
                });
#pragma warning restore 612, 618
        }
    }
}
